---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-dump-kubexdp-io-v1alpha1-dump
  failurePolicy: Fail
  name: mdump-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dump.kubexdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dumps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dump-kubexdp-io-v1alpha1-dump
  failurePolicy: Fail
  name: vdump-v1alpha1.kb.io
  rules:
  - apiGroups:
    - dump.kubexdp.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dumps
  sideEffects: None
