---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gpu-obs-gpu-v1alpha1-cudaebpfpolicy
  failurePolicy: Fail
  name: mcudaebpfpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gpu.obs.gpu
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cudaebpfpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gpu-obs-gpu-v1alpha1-cudaebpfpolicy
  failurePolicy: Fail
  name: vcudaebpfpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gpu.obs.gpu
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cudaebpfpolicies
  sideEffects: None
