# This rule is not used by the project kubexdp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the dump.kubexdp.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubexdp
    app.kubernetes.io/managed-by: kustomize
  name: dump-editor-role
rules:
- apiGroups:
  - dump.kubexdp.io
  resources:
  - dumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dump.kubexdp.io
  resources:
  - dumps/status
  verbs:
  - get
