# This rule is not used by the project gpu-bpf-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gpu.obs.gpu resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-bpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: probetargetbinding-viewer-role
rules:
- apiGroups:
  - gpu.obs.gpu
  resources:
  - probetargetbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpu.obs.gpu
  resources:
  - probetargetbindings/status
  verbs:
  - get
