apiVersion: gpu.obs.gpu/v1alpha1
kind: ProbeTargetBinding
metadata:
  labels:
    app.kubernetes.io/name: gpu-bpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: probetargetbinding-sample
spec:
  # TODO(user): Add fields here
