# This rule is not used by the project gpu-bpf-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gputrace.gputracing.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gpu-bpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: gputracepolicy-editor-role
rules:
- apiGroups:
  - gputrace.gputracing.io
  resources:
  - gputracepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gputrace.gputracing.io
  resources:
  - gputracepolicies/status
  verbs:
  - get
